services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine3.17
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5452:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - services

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - services

  eureka-server:
    image: cassioate/eureka-server:latest
    container_name: eureka-server
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - services
    depends_on:
      - zipkin

  apigateway:
    image: cassioate/apigateway:latest
    container_name: apigateway
    ports:
      - 8000:8000
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - services
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: cassioate/customer:latest
    container_name: customer
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - services
      - postgres
    depends_on:
      - postgres
      - zipkin
      - eureka-server
      - rabbitmq

  fraud:
    image: cassioate/fraud:latest
    container_name: fraud
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - services
      - postgres
    depends_on:
      - postgres
      - zipkin
      - eureka-server
      - rabbitmq

  notification:
    image: cassioate/notification:latest
    container_name: notification
    ports:
      - 8082:8082
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - services
      - postgres
    depends_on:
      - postgres
      - zipkin
      - eureka-server

networks:
  postgres:
    driver: bridge
  services:
    driver: bridge

volumes:
  postgres:
  pgadmin: